### ISSUE TITLE
Missing option

### ISSUE THREAD

**Issue by eric-vader** [guoyongcs/LCCGAN#1]
Line 139 of `trainer.py`:

```
loss = 0.5 * l1 + self.opt.MU * l2 + self.opt.LCCLAMBDA * l3
```

`self.opt.MU` is not declared, seems not to be a valid option. I have tried to find out from your paper and couldn't find it too!

**Comment by guoyongcs** [comment]
Here, self.opt.MU corresponds to L_G in Eqn. (2). We will update the name in our code.
